### ISSUE TITLE
Unknown country and Tor network support

### ISSUE THREAD

**Issue by Hill-98** [missuo/OpenAI-Checker#1]
As described by https://support.cloudflare.com/hc/en-us/articles/200168236-Configuring-IP-geolocation, `XX` is used for clients without country codes and `T1` is used for TOR network clients, both of which unlock ChatGPT according to my tests, should these two codes be added to the script.

**Comment by missuo** [comment]
Thank you for the correction. I'll add it. @Hill-98

**Comment by Hill-98** [comment]
@missuo `XX` and `T1` are banned in ChatGPT now, so please restore them.

PS: `XX` and `T1` can now use ChatGPT, but cannot log in.

**Comment by Hill-98** [comment]
Well, I found out that as long as ChatGPT is successfully logged in, it does not double check the IP location afterwards, and even a Chinese IP can use it.

**Comment by missuo** [comment]
So now it's confirmed that `XX` and `T1` can access ChatGPT, but not log in, right?

**Comment by Hill-98** [comment]
Yes, OpenAI only checks user location at login.
