### ISSUE TITLE
Dou consider adding a request timeout setting and judgment?

### ISSUE THREAD

**Issue by spiritLHLS** [missuo/OpenAI-Checker#2]
Hi, in your code
```
iso2_code4=$(curl -4 -sS https://chat.openai.com/cdn-cgi/trace | grep "loc=" | awk -F= '{print $2}')
```
```
iso2_code6=$(curl -6 -sS https://chat.openai.com/cdn-cgi/trace | grep "loc=" | awk -F= '{print $2}') 
```
does not add timeout setting, it may block the run for a long time, do you consider adding a request timeout setting and judgment?

Otherwise the following will occur:
![图片](https://user-images.githubusercontent.com/103393591/220078341-9f2c56f8-ba51-4980-8f9e-b2e4d8a073bd.png)

**Comment by missuo** [comment]
This is a very good suggestion. I'll optimize it later when I have time. @spiritLHLS

**Comment by spiritLHLS** [comment]
Any progress?

**Comment by missuo** [comment]
I'm sorry about that. You have to understand that this is an open source project, not my work.

**Comment by spiritLHLS** [comment]
I understand and thank you for the project.
