### ISSUE TITLE
it is not accessible on mobile phones

### ISSUE THREAD

**Issue by charley008** [missuo/OpenAI-Checker#6]
After the server executes the script, it shows that it can access chat.openai.com, and the PC side is indeed normal. However, it is not accessible on mobile phones

**Comment by charley008** [comment]
手机访问chatgpt ，会在这里检查https://ios.chat.openai.com/public-api/mobile/server_status/v1 ，三种情况：
1，vps完全不能访问chatgpt，包括app。
        "message": "OpenAI’s services are not available in your country or region.",
        "error_type": "unsupported_country"
2， vps可以访问chatgpt，但是手机的chatgpt app不可以使用。
        "cf_details":"Something went wrong. You may be connected to a disallowed ISP. If you are using VPN, try disabling it. 
    Otherwise try a different Wi-Fi network or data connection.
3， 完全可以使用chatgpt 的app
     {"status":"normal","message":null,"button_url":null,"button_title":null}

**Comment by missuo** [comment]
With the update of OpenAI's strategy, this script may no longer be accurate. (May 29, 2023)

**Comment by charley008** [comment]
```bash
#!/bin/bash

# 目标URL
url="https://ios.chat.openai.com/public-api/mobile/app_support_status/v1"
# 最大请求时间（秒）
timeout=10

# 发送请求并获取响应内容，设置最大请求时间
response=$(curl -s --max-time $timeout $url)

# 检查请求是否超时
if [ $? -eq 28 ]; then
    echo "无法访问服务器，连接超时。"
    exit 1
fi

# 检查响应内容
if echo "$response" | grep -q '"status":"supported"'; then
    echo "手机端和PC端都可以访问ChatGPT服务。"
elif echo "$response" | grep -q 'Something went wrong. You may be connected to a disallowed ISP.'; then
    echo "手机端不可以访问，PC端可以正常使用ChatGPT服务。"
elif echo "$response" | grep -q 'OpenAI’s services are not available in your country or region.'; then
    echo "手机端和PC端都不可以访问ChatGPT服务。"
else
    echo "无法确定ChatGPT服务的可用性。"
fi
